# Generated by Django 3.0.3 on 2020-02-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WMSCRS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WMSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255, unique=True)),
                ('server_baseurl', models.URLField()),
                ('server_version', models.CharField(choices=[('', 'WMS Version'), ('1.1.1', '1.1.1'), ('1.3.0', '1.3.0')], max_length=5)),
                ('server_title', models.CharField(max_length=255)),
                ('server_abstract', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WMSLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255, unique=True)),
                ('layer_visible', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=5)),
                ('layers', models.CharField(max_length=255)),
                ('styles', models.CharField(blank=True, max_length=255, null=True)),
                ('crs', models.CharField(max_length=20)),
                ('format', models.CharField(choices=[('', 'Image Format'), ('image/gif', 'image/gif'), ('image/jpeg', 'image/jpeg'), ('image/png', 'image/png'), ('image/png8', 'image/png8 (Recommended)'), ('image/vnd.jpeg-png', 'image/vnd.jpeg-png'), ('image/vnd.jpeg-png8', 'image/vnd.jpeg-png8')], max_length=50)),
                ('transparent', models.BooleanField(default=True)),
                ('sld', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('cql_filter', models.TextField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gj_layers.WMSServer')),
            ],
        ),
    ]
