# Generated by Django 3.0.3 on 2020-02-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gj_layers', '0002_auto_20200218_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wmslayer',
            old_name='crs',
            new_name='src',
        ),
    ]
