# Generated by Django 3.0.3 on 2020-02-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gj_layers', '0006_remove_wmslayer_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wmslayer',
            old_name='layer_visible',
            new_name='visible',
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='sld',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sld'),
        ),
    ]
