# Generated by Django 3.0.3 on 2020-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gj_layers', '0007_auto_20200218_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmslayer',
            name='version',
            field=models.CharField(choices=[('', 'WMS Version'), ('1.1.1', '1.1.1'), ('1.3.0', '1.3.0')], max_length=5),
        ),
    ]
