# Generated by Django 3.0.3 on 2020-02-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gj_layers', '0008_auto_20200218_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmscrs',
            options={'ordering': ['crs']},
        ),
        migrations.AddField(
            model_name='wmscrs',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
