# Generated by Django 3.0.3 on 2020-02-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gj_layers', '0009_auto_20200218_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='XYZLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255, unique=True)),
                ('server', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='wmslayer',
            old_name='visible',
            new_name='layer_visible',
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='layer_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='layer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='layer_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wmsserver',
            name='server_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wmsserver',
            name='server_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
