# Generated by Django 3.0.3 on 2020-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gj_layers', '0010_auto_20200227_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='layer_opacity',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
